config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :accounts, only: [:index, :show]
  resources :transfers, only: [:create]

  root 'accounts#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :transfers_from, class_name: "Transfer", foreign_key: "from_account_id", dependent: :destroy
  has_many :transfers_to, class_name: "Transfer", foreign_key: "to_account_id", dependent: :destroy

  validates :number, presence: true, uniqueness: true
  validates :initial_balance, numericality: { greater_than_or_equal_to: 0 }

  def balance
    initial_balance + transfers_to.sum(:amount) - transfers_from.sum(:amount)
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/transfer.rb
class Transfer < ApplicationRecord
  belongs_to :from_account, class_name: "Account"
  belongs_to :to_account, class_name: "Account"

  validates :from_account, presence: true
  validates :to_account, presence: true
  validates :amount, numericality: { greater_than: 0 }, presence: true
  validate :validate_sufficient_funds

  scope :account, -> (account_id) {where("from_account_id = ? OR to_account_id = ?", account_id, account_id)}

  def validate_sufficient_funds
    if from_account_id && Account.exists?(from_account_id) && amount.present?
      from_account = Account.find(from_account_id)
      if from_account.balance < amount
        errors.add(:from_account, "does not have enough funds") if from_account.balance < amount
      end
    end
  end


end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @accounts = Account.all
  end

  def show
    @account = Account.find(params[:id])
    @transfers = Transfer.account(@account.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  require 'csv'

  def create
    csv_file = params[:file]

    # Ensure that a CSV file was uploaded
    if csv_file.content_type != 'text/csv'
      flash[:error] = 'Please upload a CSV file'
      redirect_to accounts_path and return
    end

    errors = []
    CSV.foreach(csv_file.path, headers: false).with_index do |row, i|
      transfer = create_transfer(row)
      if transfer.errors.present?
        errors << "Row #{i + 1} cannot be processed: #{transfer.errors.full_messages.to_sentence}"
      end
    end
    flash[:notice] = "CSV file uploaded successfully. #{('Errors been found:' + errors.to_s) if errors.present?}"
    redirect_to accounts_path
  end

  private

  def create_transfer(row)
    from_account = Account.find_by(number: row[0])
    to_account = Account.find_by(number: row[1])
    Transfer.create(
      from_account: from_account,
      to_account: to_account,
      amount: row[2].try(:to_f)
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/index.html.erb
<h1>Accounts</h1>

  <table class="mableTable">
    <tr>
      <th style="text-align: left">Account Number</th>
      <th>Balance</th>
    </tr>
    <% @accounts.each do |account| %>
    <tr>
      <td style="text-align: left"><%= link_to account.number, account_path(id:account.id) %></td>
      <td><%= number_to_currency(account.balance) %></td>
    </tr>
    <% end %>
  </table>

  <h2>Import Transfers</h2>
  <%= form_tag(transfers_path, multipart:true, method: 'post') do %>
    <%= file_field_tag :file, class: 'input' %>
    <%= submit_tag "Upload" %>
  <% end %>

  <% if flash.present? %>
    <h2> Result: </h2>
    <% flash.each do |key, value| %>
      <% flash_value = value  %>
      <%= content_tag :div, flash_value.to_s.html_safe, class: "flash #{key}" %>
    <% end %>
  <% end %>

app/views/accounts/show.html.erb
<h1>Account <%= @account.number %></h1>

<h2> Transfers</h2>

    <table class="mableTable">
      <tr><th style="text-align: left">From</th><th style="text-align: left">To</th><th>Amount</th></tr>
      <tr><td style="text-align: left" colspan="2">Initial Balance </td><td><%= @account.initial_balance %></td></tr>
      <% @transfers.each do |transfer| %>
        <tr>
          <td style="text-align: left"><%= link_to transfer.from_account.number, account_path(id:transfer.from_account_id) %></td>
          <td style="text-align: left"><%= link_to transfer.to_account.number, account_path(id:transfer.to_account_id) %></td>
          <td><%= '- ' if transfer.from_account == @account %> <%= transfer.amount %></td>
        </tr>
      <% end %>
      <tr><td style="text-align: left" colspan="2">Final Balance </td><td><b><%= @account.balance %></b></td></tr>
    </table>

<br>

<%= link_to 'Back to Accounts', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TransferApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>